joint_poses:
  - [0.0005, -0.2010, 0.0002, -2.4344, -0.0006, 2.2261, 0.7006]
  - [-0.2241, -0.1938, -0.0004, -2.4256, 0.2794, 2.1497, 0.3113]
  - [-0.2036, 0.0492, -0.0005, -2.1118, 0.1968, 1.8666, 0.4366]
  - [-0.1926, 0.0967, -0.0005, -1.8828, 0.0666, 1.6413, 0.1101]
  - [-0.2908, 0.1115, -0.0005, -1.8834, 0.3125, 1.6100, 0.0734]
  - [0.0472, 0.3893, -0.0003, -1.6279, -0.1268, 1.5852, 0.8351]
  - [0.0643, -0.6631, -0.0004, -2.8833, -0.3005, 2.4016, 1.0992]
  - [0.5044, -0.4669, -0.0005, -2.7071, -0.5704, 2.1515, 1.6473]
  - [0.3697, 0.2199, -0.0003, -1.8874, -0.2827, 1.6856, 1.1575]
  - [0.0010, -0.0735, -0.0002, -2.0803, -0.0020, 2.0001, 0.1125]
  - [0.1112, 0.2672, 0.0003, -1.6263, -0.2916, 1.5173, 0.2043]
  - [-0.5300, -0.4270, -0.0079, -2.4486, 0.5668, 1.7413, -0.4736]
