joint_poses:
  - [0.0006, -0.2010, 0.0003, -2.4346, -0.0012, 2.2251, 0.7005]
  - [-0.2239, -0.1940, -0.0001, -2.4261, 0.2786, 2.1502, 0.3117]
  - [-0.2037, 0.0490, -0.0002, -2.1123, 0.1976, 1.8674, 0.4362]
  - [-0.1926, 0.0965, -0.0002, -1.8833, 0.0674, 1.6421, 0.1105]
  - [-0.2905, 0.1113, -0.0002, -1.8836, 0.3118, 1.6112, 0.0738]
  - [0.0470, 0.3892, -0.0001, -1.6283, -0.1259, 1.5871, 0.8345]
  - [0.0641, -0.6631, -0.0002, -2.8831, -0.2995, 2.4007, 1.0988]
  - [0.5042, -0.4673, -0.0002, -2.7075, -0.5694, 2.1524, 1.6468]
  - [0.3700, 0.2197, -0.0000, -1.8879, -0.2834, 1.6866, 1.1579]
  - [0.0012, -0.0732, 0.0000, -2.0800, -0.0027, 1.9994, 0.1129]
  - [0.1111, 0.2669, 0.0004, -1.6269, -0.2907, 1.5181, 0.2039]
  - [-0.5297, -0.4268, -0.0075, -2.4483, 0.5659, 1.7401, -0.4732]
  - [-0.5297, -0.4268, -0.0076, -2.4483, 0.5660, 1.7401, -0.4732]
